from datetime import datetime


# ==========================================================
# EXECUTIVE SUMMARY
# ==========================================================

def executive_summary(

    latest_round,

    forecast_year,

    forecast_season,

    historical_fcs,

    historical_rcsi,

    historical_hhs,

    forecast_fcs,

    forecast_rcsi,

    forecast_hhs,

    overall_risk,

    dominant,

    top_driver

):

    return f"""

The latest available historical food security assessment ({latest_round})
indicates national average food security outcomes of:

• Food Consumption Score (FCS): {historical_fcs:.2f}

• Reduced Coping Strategy Index (rCSI): {historical_rcsi:.2f}

• Household Hunger Scale (HHS): {historical_hhs:.2f}

Machine learning forecasts generated by the Food Security Forecasting
and Decision Support System (FSFDSS) suggest the following outlook for
{forecast_season} {forecast_year}:

• Forecast Food Consumption Score (FCS): {forecast_fcs:.2f}

• Forecast Reduced Coping Strategy Index (rCSI): {forecast_rcsi:.2f}

• Forecast Household Hunger Scale (HHS): {forecast_hhs:.2f}

Overall forecast risk is classified as:

{overall_risk.upper()}

Model interpretation using SHAP values indicates that
{dominant.lower()} drivers remain the dominant determinants of
forecast food security outcomes.

The single most influential predictor identified by the XGBoost
forecasting models is:

{top_driver}

These findings suggest that continued monitoring of environmental
conditions, market dynamics, household livelihood resilience and
conflict patterns will remain essential for supporting timely
food security decision-making.

This report was automatically generated by the Food Security
Forecasting and Decision Support System (FSFDSS) on

{datetime.now():%d %B %Y at %H:%M}.

"""